version: '3'
services:
  kamailio:
    container_name: kamailio
    image: kamailio:v5.7.2
    privileged: true
    restart: always
    volumes:
      - $PWD/kamailio:/etc/kamailio
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    network_mode: host
  kamsql:
    container_name: kamsql
    image: mysql:5.7.31
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MyNewPass4!
      - MYSQL_DATABASE=kamailio
      - MYSQL_USER=kamailio
      - MYSQL_PASSWORD=Kamailiorw4!
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    ports:
      - 3306:3306
    networks:
      - kamnet
    volumes:
      - $PWD/mysql/data:/var/lib/mysql
      - $PWD/mysql/config:/etc/mysql/conf.d
      - $PWD/mysql/init:/docker-entrypoint-initdb.d
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M

networks:
  kamnet:
    external:
      name: kamailio_net
